=== sogis/qwc_services/config-generator-agent/schemas/sogis-config-generator.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://git.sourcepole.ch/ktso/somap/-/raw/master/config-generator/schemas/sogis-config-generator.json",
  "title": "SO!GIS Config generator",
  "type": "object",
  "properties": {
    "$schema": {
      "title": "JSON Schema",
      "description": "Reference to JSON schema of this config",
      "type": "string",
      "format": "uri",
      "default": "https://git.sourcepole.ch/ktso/somap/-/raw/master/config-generator/schemas/sogis-config-generator.json"
    },
    "service": {
      "title": "Service name",
      "type": "string",
      "const": "config-generator"
    },
    "config": {
      "title": "Config options for Config generator",
      "type": "object",
      "properties": {
        "config_db_url": {
          "description": "Connection URL for configuration database. Example: postgresql:///?service=soconfig_services",
          "type": "string",
          "format": "uri"
        },
        "config_path": {
          "description": "Target path for service configs and permissions. Example: /etc/qwc_service/",
          "type": "string"
        },
        "legend_images_path": {
          "description": "Target path for custom legend images. Example: /qgs-resources/",
          "type": "string"
        },
        "default_qgis_server_url": {
          "description": "Default QGIS Server URL used for OGC, FeatureInfo an Legend service configs if not specified there. Example: http://sogis-qgis-server/ows/",
          "type": "string",
          "format": "uri"
        }
      },
      "required": [
        "config_db_url",
        "config_path",
        "legend_images_path"
      ]
    },
    "services": {
      "title": "Service configs",
      "description": "Service specific config options for generating their service configs",
      "type": "array",
      "items": {
        "description": "Generator config for a service",
        "oneOf": [
          {"$ref": "#/definitions/common_service"},
          {"$ref": "#/definitions/mapViewer"},
          {"$ref": "#/definitions/ogc"}
        ]
      }
    },
    "qgs_writer": {
      "title": "QGSWriter config",
      "description": "Config options for generating QGIS project files",
      "type": "object",
      "properties": {
        "project_output_dir": {
          "description": "Target path for QGIS project files. Example: /qgs-resources/",
          "type": "string"
        },
        "default_extent": {
          "description": "Default layer extent, in the format [xmin,ymin,xmax,ymax]. Example: [2590983, 1212806, 2646267, 1262755]",
          "type": "array",
          "items": {
            "type": "number"
          },
          "minItems": 4,
          "maxItems": 4
        },
        "default_raster_extent": {
          "description": "Optional extent for raster layers, in the format [xmin,ymin,xmax,ymax]. Example: [2590000, 1210000, 2650000, 1270000]",
          "type": "array",
          "items": {
            "type": "number"
          },
          "minItems": 4,
          "maxItems": 4
        },
        "selection_color": {
          "description": "Project selection color, also used for server highlighting, in the format [r,g,b,a]. Example: [255, 255, 0, 255]",
          "type": "array",
          "items": {
            "type": "integer"
          },
          "minItems": 4,
          "maxItems": 4
        }
      },
      "required": [
        "project_output_dir"
      ]
    }
  },
  "required": [
    "service",
    "config",
    "services",
    "qgs_writer"
  ],
  "definitions": {
    "common_service": {
      "description": "Generator config for a QWC service",
      "type": "object",
      "properties": {
        "name": {
          "description": "Service name",
          "type": "string",
          "enum": [
            "agdi",
            "ccc",
            "data",
            "dataproduct",
            "document",
            "elevation",
            "featureInfo",
            "landreg",
            "legend",
            "mapinfo",
            "permalink",
            "plotinfo",
            "print",
            "saml-auth",
            "search"
          ]
        },
        "config": {
          "description": "QWC service config options (cf. its JSON schema). This is copied unmodified to the service config.",
          "type": "object"
        }
      },
      "required": [
        "name",
        "config"
      ]
    },
    "mapViewer": {
      "description": "Generator config for Map Viewer",
      "type": "object",
      "properties": {
        "name": {
          "description": "Service name",
          "type": "string",
          "const": "mapViewer"
        },
        "config": {
          "description": "Map Viewer config options (cf. JSON schema qwc-map-viewer.json). This is copied unmodified to the service config.",
          "type": "object"
        },
        "resources": {
          "description": "Additional config for generating MapViewer resources",
          "type": "object",
          "properties": {
            "qwc2_config": {
              "description": "Additional config for QWC2 application configuration",
              "type": "object",
              "properties": {
                "qwc2_config_file": {
                  "description": "Path to QWC2 config.json file. Example: /sogis-qwc2-app/config.json",
                  "type": "string"
                },
                "wmsDpi": {
                  "description": "Optional DPI setting for WMS. Example: 96",
                  "type": "integer"
                },
                "minResultsExanded": {
                  "description": "Optional number of search results shown expanded. Example: 100",
                  "type": "integer"
                }
              },
              "required": [
                "qwc2_config_file"
              ]
            },
            "qwc2_themes": {
              "description": "Additional config for QWC2 themes configuration",
              "type": "object",
              "properties": {
                "default_theme_attribution_title": {
                  "description": "Default theme attribution title. Example: 'Kt. Solothurn'",
                  "type": "string"
                },
                "default_theme_attribution_online_resource": {
                  "description": "Default theme attribution URL. Example: https://www.so.ch/verwaltung/bau-und-justizdepartement/amt-fuer-geoinformation/geoportal/",
                  "type": "string",
                  "format": "uri"
                },
                "default_crs": {
                  "description": "Default CRS. Example: EPSG:2056",
                  "type": "string"
                },
                "default_theme_item_bounds": {
                  "description": "Default theme extent, in the format [xmin,ymin,xmax,ymax]. Example: [2590000, 1210000, 2650000, 1270000]",
                  "type": "array",
                  "items": {
                    "type": "number"
                  },
                  "minItems": 4,
                  "maxItems": 4
                },
                "default_layer_bounds": {
                  "description": "Default layer extent, in the format [xmin,ymin,xmax,ymax]. Example: [2590000, 1210000, 2650000, 1270000]",
                  "type": "array",
                  "items": {
                    "type": "number"
                  },
                  "minItems": 4,
                  "maxItems": 4
                },
                "default_image_formats": {
                  "description": "Default WMS image formats. Example: ['image/jpeg', 'image/png']",
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "default_theme": {
                  "description": "Name of default theme. Example: default",
                  "type": "string"
                },
                "default_print_layout": {
                  "description": "Name of default print layout. Example: 'A4 hoch'",
                  "type": "string"
                },
                "default_scales": {
                  "description": "Default map scales. Example: [4000000, 2000000, ..., 250, 100]",
                  "type": "array",
                  "items": {
                    "type": "integer"
                  }
                },
                "default_wms_version": {
                  "description": "Default WMS version. Example: 1.3.0",
                  "type": "string"
                },
                "default_print_resolutions": {
                  "description": "Default print resolutions. Example: [300]",
                  "type": "array",
                  "items": {
                    "type": "integer"
                  }
                },
                "default_print_grid": {
                  "description": "Default print grid. Example: [{s: 50000, x: 5000, y: 5000}]",
                  "type": "array",
                  "items": {
                    "description": "Print grid settings for scale",
                    "type": "object",
                    "properties": {
                      "s": {
                        "description": "Print grid scale",
                        "type": "integer"
                      },
                      "x": {
                        "description": "Print grid size in x direction",
                        "type": "integer"
                      },
                      "y": {
                        "description": "Print grid size in y direction",
                        "type": "integer"
                      }
                    },
                    "required": [
                      "s",
                      "x",
                      "y"
                    ]
                  }
                }
              }
            }
          },
          "required": [
            "qwc2_config"
          ]
        }
      },
      "required": [
        "name",
        "config"
      ]
    },
    "ogc": {
      "description": "Generator config for Data service",
      "type": "object",
      "properties": {
        "name": {
          "description": "Service name",
          "type": "string",
          "const": "ogc"
        },
        "config": {
          "description": "OGC service config options (cf. JSON schema qwc-ogc-service.json). This is copied unmodified to the service config.",
          "type": "object"
        },
        "resources": {
          "description": "Additional config for generating OGC resources",
          "wms_services": {
            "title": "WMS services",
            "type": "array",
            "items": {
              "title": "WMS service",
              "description": "Additional config for WMS service",
              "type": "object",
              "properties": {
                "name": {
                  "description": "WMS service name",
                  "type": "string"
                },
                "online_resources": {
                  "description": "Custom OnlineResources shown in GetCapabilities",
                  "type": "object",
                  "properties": {
                    "service": {
                      "description": "Default public base URL for OnlineResources",
                      "type": "string",
                      "format": "uri"
                    },
                    "feature_info": {
                      "description": "Public base URL for FeatureInfo OnlineResources",
                      "type": "string",
                      "format": "uri"
                    },
                    "legend": {
                      "description": "Public base URL for Legend OnlineResources",
                      "type": "string",
                      "format": "uri"
                    }
                  }
                }
              },
              "required": [
                "name"
              ]
            }
          },
          "wfs_services": {
            "title": "WFS services",
            "type": "array",
            "items": {
              "title": "WFS service",
              "description": "Additional config for WFS service",
              "type": "object",
              "properties": {
                "name": {
                  "description": "WFS service name",
                  "type": "string"
                },
                "online_resource": {
                  "description": "Custom OnlineResource shown in GetCapabilities",
                  "type": "string",
                  "format": "uri"
                }
              },
              "required": [
                "name"
              ]
            }
          }
        }
      },
      "required": [
        "name"
      ]
    }
  }
}

=== sogis/qwc_services/config-generator-agent/configGeneratorConfig.json
{
      "$schema": "https://git.sourcepole.ch/ktso/somap/-/raw/master/config-generator/schemas/sogis-config-generator.json",      
      "service": "config-generator",
      "config": {
          "config_db_url": "postgresql:///?service=soconfig_services",
          "config_path": "/srv/qwc_service/config",
          "legend_images_path": "/srv/qwc_service/config/default"
      },
      "services": [
      {   
        "name": "agdi",
        "config": {
            "db_url": "postgresql:///?service=soconfig_services",
            "project_output_dir": "/qgs-resources",
            "jasper_reports_dir": "/jasper/reports",
            "jasper_service_url": "http://jasper-reporting-service.gdi-test.svc/reports",
            "config_generator_url": "http://jenkins-agi-apps-test.dev.so.ch/job/print-service/buildWithParameters?token=tokenName&build=ja&namespace=gdi-test",
            "solr_update_url": "http://indexupdater.solr-cloud-test.svc/queue?ds=foreground,background&dih=solr/gdi/dih_metadata"
        }
      },
      {   
        "name": "saml-auth",
        "config": {
          "saml_path": "saml",
          "saml_slo": true,
          "group_attr": "department_qualified"
        }
      },
      {   
        "name": "ogc",
        "config": {
          "default_qgis_server_url": "http://qgis-server.gdi-test.svc/ows/"
        },
        "resources": {
          "wms_services": [
            {
              "name": "somap",
              "online_resources": {
                "service": "https://geo-t.so.ch/api/wms",
                "feature_info": "https://geo-t.so.ch/api/v1/featureinfo/somap",
                "legend": "https://geo-t.so.ch/api/v1/featureinfo/somap"
              }
            }
          ],
          "wfs_services": [
            {
              "name": "somap",
              "online_resource": "https://geo-t.so.ch/api/wfs"
            }
          ]
        }
      },
      {
        "name": "data",
        "config": {}
      },
      {
        "name": "legend",
        "config": {
          "default_qgis_server_url": "http://qgis-server.gdi-test.svc/ows/",
          "legend_images_path": "/qgs-resources/"
        }
      },
      {
        "name": "featureInfo",
        "config": {
          "default_qgis_server_url": "http://qgis-server.gdi-test.svc/ows",
          "#default_info_template": "<table>...</table>"
        }
      },
      {
      "name": "mapViewer",
        "config": {
          "qwc2_path": "/qwc2/",
          "auth_service_url": "/auth/",
          "ccc_config_service_url": "/api/v1/ccc/",
          "data_service_url": "/api/data/v1/",
          "dataproduct_service_url": "/api/dataproduct/v1/",
          "elevation_service_url": "/elevation/",
          "feature_report_service_url": "/api/v1/document/",
          "info_service_url": "/api/v1/featureinfo/",
          "landreg_service_url": "/api/v1/landreg/",
          "legend_service_url": "/api/v1/legend/",
          "mapinfo_service_url": "/api/v1/mapinfo/",
          "ogc_service_url": "/ows/",
          "permalink_service_url": "/api/v1/permalink/",
          "plotinfo_service_url": "/api/v1/plotinfo/",
          "print_service_url": "/api/v1/print/",
          "search_service_url": "/api/search/v2/fts/",
          "search_data_service_url": "/api/data/v1/"
        },
        "resources": {
          "qwc2_config": {
            "qwc2_config_file": "/srv/qwc_service/config.json",
            "wmsDpi": 96,
            "minResultsExanded": 100
          },
          "qwc2_themes": {
            "default_theme_attribution_title": "Kt. Solothurn",
            "default_theme_attribution_online_resource": "https://www.so.ch/verwaltung/bau-und-justizdepartement/amt-fuer-geoinformation/geoportal/",
            "default_crs": "EPSG:2056",
            "default_theme_item_bounds": [2590000, 1210000, 2650000, 1270000],
            "default_layer_bounds": [2590000, 1210000, 2650000, 1270000],
            "default_image_formats": ["image/jpeg", "image/png"],
            "default_theme": "default",
            "default_print_layout": "A4 hoch",
            "default_scales": [
              4000000, 2000000, 1000000, 400000, 200000, 80000, 40000, 20000, 10000, 8000, 6000, 4000, 2000, 1000, 500, 250, 100
            ],
            "default_wms_version": "1.3.0",
            "default_print_resolutions": [200],
            "backgroundLayers": [
              {
                "name": "hintergrundkarte_sw", 
                "originX": 2420000, 
                "originY": 1350000, 
                "projection": "EPSG:2056",
                "resolution": [
                   4000,2000,1000,500,250,100,50,20,10,5,2.5,1,0.5,0.25,0.1
                   ],
                "thumbnail": "img/custommapthumbs/e53e11fc-0a48-49e3-941b-9350c9eaebad.png",
                "tileMatrixPrefix": "",
                "tileMatrixSet": "2056",
                "tileSize": [256,256],
                "title": "Karte SW",
                "type": "wmts",
                "url":"https://geo-t.so.ch/api/wmts/1.0.0/ch.so.agi.hintergrundkarte_sw/default/{TileMatrixSet}/{TileMatrix}/{TileRow}/{TileCol}.png"
               }
            ],
            "default_print_grid": [
              {"s": 100000001, "x": 10000000, "y": 10000000},
              {"s": 50000001, "x": 5000000, "y": 5000000},
              {"s": 10000001, "x": 2500000, "y": 2500000},
              {"s": 5000001, "x": 250000, "y": 250000},
              {"s": 1000001, "x": 100000, "y": 100000},
              {"s": 500001, "x": 50000, "y": 50000},
              {"s": 100001, "x": 10000, "y": 10000},
              {"s": 50001, "x": 5000, "y": 5000},
              {"s": 25001, "x": 2000, "y": 2000},
              {"s": 12001, "x": 2000, "y": 2000},
              {"s": 5001, "x": 1000, "y": 1000},
              {"s": 2501, "x": 500, "y": 500},
              {"s": 1001, "x": 200, "y": 200},
              {"s": 501, "x": 100, "y": 100},
              {"s": 251, "x": 50, "y": 50},
              {"s": 100, "x": 25, "y": 25}
            ]
          }
        }
      },
      {
        "name": "search",
        "config": {
          "solr_service_url": "http://solr-headless.solr-cloud-test:8983/solr/gdi/select",
          "search_result_limit": 25,
          "geodb_url": "postgresql:///?service=soconfig_services"
        }
      },
      {
        "name": "dataproduct",
        "config": {
          "wms_service_url": "https://geo-t.so.ch/api/wms?",
          "qgs_resources_dir": "/qgs-resources/"
        }
      },
      {
        "name": "document",
        "config": {
          "jasper_service_url": "http://jasper-reporting-service.gdi-test.svc/reports",
          "jasper_timeout": 1200
        }
      },
      {
        "name": "ccc",
        "config": {
          "clients": [
            {
              "id": "baugk",
              "cccServer": "wss://geo-i.so.ch/ccc-service",
              "title": "BauGK - GIS",
              "map": "baugk",
              "editGeomType": "Point",
              "notifyLayers": [{
                "layer": "ch.so.afu.baugk.geschaefte",
                "mapping": [
                  {
                    "agdi_attr_name": "laufnummer",
                    "ccc_attr_name": "geschaeft_laufnr"
                  }
                ]
              }],
              "notifyLinkTitle": "In Axioma anzeigen"
            },
            {
              "id": "uplus_anlage",
              "cccServer": "wss://geo-i.so.ch/ccc-service",
              "title": "Umweltplus - GIS",
              "map": "ews_v2",
              "editGeomType": "Point",
              "notifyLayers": [{
                "layer": "ch.so.afu.erdwaerme.uplus.anlage_v2",
                "mapping": [
                  {
                    "agdi_attr_name": "anlage_uuid",
                    "ccc_attr_name": "uplus_anlage"
                  }
                ]
              }],
              "notifyLinkTitle": "In Umweltplus anzeigen"
            },
            {
              "id": "uplus_tank",
              "cccServer": "wss://geo-i.so.ch/ccc-service",
              "title": "Umweltplus - GIS",
              "map": "uplus_tank",
              "editGeomType": "Point",
	      "notifyLayers": [{
                "layer": "ch.so.afu.uplus.tank",
                "mapping": [
                  {
                    "agdi_attr_name": "anlage_uuid",
                    "ccc_attr_name": "uplus_anlage"
                  }
                ]
              }],
              "notifyLinkTitle": "In Umweltplus anzeigen"
            },
            {
              "id": "uplus_luft",
              "cccServer": "wss://geo-i.so.ch/ccc-service",
              "title": "Umweltplus - GIS",
              "map": "uplus_luft",
              "editGeomType": "Point",
              "notifyLayers": [{
                "layer": "ch.so.afu.uplus.luft_anlage",
                "mapping": [
                  {
                    "agdi_attr_name": "anlage_uuid",
                    "ccc_attr_name": "uplus_anlage"
                  }
                ]
              }, {
                "layer": "ch.so.afu.uplus.luft_betrieb",
                "mapping": [
                  {
                    "agdi_attr_name": "betrieb_uuid",
                    "ccc_attr_name": "uplus_betrieb"
                  }
                ]
              }],
              "notifyLinkTitle": "In Umweltplus anzeigen"
            }
          ],
	  "zoomto_data_service_url": "http://data-service.gdi-test.svc",
          "zoomto_full_extent": [2590983.475, 1212806.115, 2646267.025, 1262755.009],
          "zoomto_config": {
            "locatorType": "PriorityLocator",
            "filters": [
              {
                "dataset": "ch.so.agi.av.grundstuecke.rechtskraeftig",
                "filter": [
                  ["nbident", "=", "{grundbuch_nbident}"], "and", ["nummer", "=", "{parzelle_nr}"]
                ]
              },
              {
